# Generated by Django 6.0.4 on 2026-05-22 08:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerapplication',
            name='aadhar_card',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aadhar_card'),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='cv',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cv'),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='driving_license',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='driving_license'),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='passport_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='passport_photo'),
        ),
    ]
